name: saadi-collection
static_sites:
  - name: saadi-collection
    source_dir: /
    build_command: npm run build
    output_dir: build
    routes:
      - path: /
        index_document: index.html
        error_document: index.html
